export const DEPARTMENTS: { group: string; items: string[] }[] = [
  {
    group: 'Technical',
    items: [
      'Software Engineering',
      'Frontend Development',
      'Backend Development',
      'Full Stack Development',
      'Mobile Development',
      'DevOps / Infrastructure',
      'Data Engineering',
      'Data Science',
      'AI / Machine Learning',
      'Cybersecurity',
      'Cloud Architecture',
      'QA / Testing',
      'UI / UX Design',
      'Product Management',
      'Blockchain',
      'Embedded Systems',
      'Network Engineering',
      'IT Support',
    ],
  },
  {
    group: 'Non-Technical',
    items: [
      'Sales',
      'Business Development',
      'Marketing',
      'Digital Marketing',
      'Content & Communications',
      'Human Resources',
      'Finance & Accounting',
      'Operations',
      'Customer Success',
      'Legal & Compliance',
      'Supply Chain / Logistics',
      'Consulting',
      'Project Management',
      'Administration',
      'Public Relations',
      'Research & Analytics',
      'Strategy',
      'Procurement',
    ],
  },
]

export const ALL_DEPARTMENTS = DEPARTMENTS.flatMap((g) => g.items)
